name: Lint

on: pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: [14.x]
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install Packages
        run: yarn install
      - name: Run linter
        run: yarn lint
