name: Cypress

on: [push, pull_request]

jobs:
  Cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Setup Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Copy .env file
        run: cp .env.test .env
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install Packages
        run: yarn install
      - name: Run Cypress
        run: yarn e2e:headless
