name: Cypress

on: [push, pull_request]

jobs:
  Cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Copy .env file
        run: cp .env.dev .env
      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true
      - name: Cypress.io
        uses: cypress-io/github-action@v4
        with:
          install: false
          build: pnpm build
          start: pnpm start
          wait-on: "http://localhost:3000"
