name: Cypress

on: [push, pull_request]

jobs:
  Cypress:
    runs-on: ubuntu-latest
    container: cypress/base:12
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: Copy .env file
        run: cp .env.dev .env
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install Packages
        run: yarn install
      - name: Cypress.io
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start
          wait-on: "http://localhost:3000"
